# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Github Action for wget
        # You may pin to the exact commit or the version.
        # uses: wei/wget@ca0a6b7f0fdd7ffbe9d4cec0b9696f2dc658d3c9
        uses: wei/wget@v1.1.1
        with:
          args: -O edgefunc.zip https://developers.limelight.com/downloads/edgefunc/prod/edgefunc-current-amd64-linux.zip
          
          
      - name: tonybogdanov-zip
        # You may pin to the exact commit or the version.
        # uses: TonyBogdanov/zip@bd7d01f6fe96c00324826a8f94cfb289d5363901
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -qq ./edgefunc.zip -d ./target
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./target/edgefunc --help

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          LLNW_USERNAME: secrets.llnw_username
          LLNW_SHORTNAME: secrets.llnw_shortname
          LLNW_API_KEY: secrets.llnw_api_key
        run: |
          ./target/edgefunc list-functions --shortname "$LLNW_SHORTNAME" --username "$LLNW_USERNAME" --control-key "$LLNW_API_KEY"
